name: Unity Test and Build

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  checks: write
  contents: read

jobs:
  setup:
    name: Verify Project Structure
    runs-on: ubuntu-latest
    outputs:
      project-valid: ${{ steps.validate.outputs.valid }}
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - id: validate
        name: Check Project Files
        run: |
          if [ -f "ProjectSettings/ProjectVersion.txt" ]; then
            echo "Project structure valid"
            echo "valid=true" >> $GITHUB_OUTPUT
          else
            echo "::error::Missing ProjectSettings/ProjectVersion.txt"
            echo "valid=false" >> $GITHUB_OUTPUT
            exit 1
          fi

  testProject:
    name: Test in ${{ matrix.testMode }}
    needs: setup
    if: needs.setup.outputs.project-valid == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode: [playmode, editmode]
        
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.testMode }}-${{ github.sha }}
          restore-keys: |
            Library-${{ matrix.testMode }}-
            Library-

      - uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          testMode: ${{ matrix.testMode }}
          artifactsPath: test-results/${{ matrix.testMode }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          unityVersion: 2022.3.21f1  # Замените на вашу версию Unity

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Test-Results-${{ matrix.testMode }}
          path: test-results/${{ matrix.testMode }}

  buildProject:
    name: Build for ${{ matrix.platform }}
    needs: testProject
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [StandaloneWindows64, StandaloneLinux64, Android]
        
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.platform }}-${{ github.sha }}
          restore-keys: |
            Library-${{ matrix.platform }}-
            Library-

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          targetPlatform: ${{ matrix.platform }}
          unityVersion: 2022.3.21f1  # Замените на вашу версию Unity

      - uses: actions/upload-artifact@v4
        with:
          name: Build-${{ matrix.platform }}
          path: build/${{ matrix.platform }}
